// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nextjs_backend.Models;

#nullable disable

namespace nextjs_backend.Migrations
{
    [DbContext(typeof(nextjstestContext))]
    partial class nextjstestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("nextjs_backend.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3958dc9e-712f-4377-85e9-fec4b6a6442a",
                            Email = "delba@oliveira.com",
                            ImageUrl = "/customers/delba-de-oliveira.png",
                            Name = "Delba de Oliveira"
                        },
                        new
                        {
                            Id = "3958dc9e-742f-4377-85e9-fec4b6a6442a",
                            Email = "lee@robinson.com",
                            ImageUrl = "/customers/lee-robinson.png",
                            Name = "Lee Robinson"
                        },
                        new
                        {
                            Id = "3958dc9e-737f-4377-85e9-fec4b6a6442a",
                            Email = "hector@simpson.com",
                            ImageUrl = "/customers/hector-simpson.png",
                            Name = "Hector Simpson"
                        },
                        new
                        {
                            Id = "50ca3e18-62cd-11ee-8c99-0242ac120002",
                            Email = "steven@tey.com",
                            ImageUrl = "/customers/steven-tey.png",
                            Name = "Steven Tey"
                        },
                        new
                        {
                            Id = "3958dc9e-787f-4377-85e9-fec4b6a6442a",
                            Email = "steph@dietz.com",
                            ImageUrl = "/customers/steph-dietz.png",
                            Name = "Steph Dietz"
                        },
                        new
                        {
                            Id = "76d65c26-f784-44a2-ac19-586678f7c2f2",
                            Email = "michael@novotny.com",
                            ImageUrl = "/customers/michael-novotny.png",
                            Name = "Michael Novotny"
                        },
                        new
                        {
                            Id = "d6e15727-9fe1-4961-8c5b-ea44a9bd81aa",
                            Email = "evil@rabbit.com",
                            ImageUrl = "/customers/evil-rabbit.png",
                            Name = "Evil Rabbit"
                        },
                        new
                        {
                            Id = "126eed9c-c90c-4ef6-a4a8-fcf7408d3c66",
                            Email = "emil@kowalski.com",
                            ImageUrl = "/customers/emil-kowalski.png",
                            Name = "Emil Kowalski"
                        },
                        new
                        {
                            Id = "CC27C14A-0ACF-4F4A-A6C9-D45682C144B9",
                            Email = "amy@burns.com",
                            ImageUrl = "/customers/amy-burns.png",
                            Name = "Amy Burns"
                        },
                        new
                        {
                            Id = "13D07535-C59E-4157-A011-F8D2EF4E0CBB",
                            Email = "balazs@orban.com",
                            ImageUrl = "/customers/balazs-orban.png",
                            Name = "Balazs Orban"
                        });
                });

            modelBuilder.Entity("nextjs_backend.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("invoices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Amount = 15795,
                            CustomerId = "3958dc9e-712f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2022, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "pending"
                        },
                        new
                        {
                            Id = "2",
                            Amount = 20348,
                            CustomerId = "3958dc9e-742f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "pending"
                        },
                        new
                        {
                            Id = "3",
                            Amount = 3040,
                            CustomerId = "3958dc9e-787f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2022, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "4",
                            Amount = 44800,
                            CustomerId = "50ca3e18-62cd-11ee-8c99-0242ac120002",
                            Date = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "5",
                            Amount = 34577,
                            CustomerId = "76d65c26-f784-44a2-ac19-586678f7c2f2",
                            Date = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "pending"
                        },
                        new
                        {
                            Id = "6",
                            Amount = 54246,
                            CustomerId = "126eed9c-c90c-4ef6-a4a8-fcf7408d3c66",
                            Date = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "pending"
                        },
                        new
                        {
                            Id = "7",
                            Amount = 666,
                            CustomerId = "d6e15727-9fe1-4961-8c5b-ea44a9bd81aa",
                            Date = new DateTime(2023, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "pending"
                        },
                        new
                        {
                            Id = "8",
                            Amount = 32545,
                            CustomerId = "50ca3e18-62cd-11ee-8c99-0242ac120002",
                            Date = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "9",
                            Amount = 1250,
                            CustomerId = "3958dc9e-787f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "10",
                            Amount = 8546,
                            CustomerId = "76d65c26-f784-44a2-ac19-586678f7c2f2",
                            Date = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "11",
                            Amount = 500,
                            CustomerId = "3958dc9e-742f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2023, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "12",
                            Amount = 8945,
                            CustomerId = "76d65c26-f784-44a2-ac19-586678f7c2f2",
                            Date = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "13",
                            Amount = 8945,
                            CustomerId = "3958dc9e-737f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "14",
                            Amount = 8945,
                            CustomerId = "3958dc9e-712f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        },
                        new
                        {
                            Id = "15",
                            Amount = 1000,
                            CustomerId = "3958dc9e-737f-4377-85e9-fec4b6a6442a",
                            Date = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "paid"
                        });
                });

            modelBuilder.Entity("nextjs_backend.Models.Revenue", b =>
                {
                    b.Property<string>("Month")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("month");

                    b.Property<int>("Revenue1")
                        .HasColumnType("int")
                        .HasColumnName("revenue");

                    b.HasKey("Month", "Revenue1");

                    b.HasIndex(new[] { "Month" }, "UQ__revenue__0DD75472E02AC0B3")
                        .IsUnique();

                    b.ToTable("revenue", (string)null);

                    b.HasData(
                        new
                        {
                            Month = "Jan",
                            Revenue1 = 2000
                        },
                        new
                        {
                            Month = "Feb",
                            Revenue1 = 1800
                        },
                        new
                        {
                            Month = "Mar",
                            Revenue1 = 2200
                        },
                        new
                        {
                            Month = "Apr",
                            Revenue1 = 2500
                        },
                        new
                        {
                            Month = "May",
                            Revenue1 = 2300
                        },
                        new
                        {
                            Month = "Jun",
                            Revenue1 = 3200
                        },
                        new
                        {
                            Month = "Jul",
                            Revenue1 = 3500
                        },
                        new
                        {
                            Month = "Aug",
                            Revenue1 = 3700
                        },
                        new
                        {
                            Month = "Sep",
                            Revenue1 = 2500
                        },
                        new
                        {
                            Month = "Oct",
                            Revenue1 = 2800
                        },
                        new
                        {
                            Month = "Nov",
                            Revenue1 = 3000
                        },
                        new
                        {
                            Month = "Dec",
                            Revenue1 = 4800
                        });
                });

            modelBuilder.Entity("nextjs_backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164F19C174A")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "410544b2-4001-4271-9855-fec4b6a6442a",
                            Email = "user@nextmail.com",
                            Name = "User",
                            Password = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
